/* =====================================================================
   THE LAST FIVE YEARS — THE SECOND SCREEN
   SHOW CONTENT · production build (David's line-by-line, Sept 18, 2026)

   RULES THIS FILE OBEYS
   1. ONE SONG, ONE DEVICE. The projection shows the singer's screen for the
      whole number. Duets flip by whoever is singing (declared per cue).
   2. NO CUTAWAYS. Jamie's clock runs forward, Cathy's runs backward — the two
      characters are never in the same moment. A song therefore only ever shows
      its own singer's device. Enforced by validatePOV().
   3. THE CLOCK IS THE PRESENT. Anything stamped earlier is history and loads
      with the app. Live typing only ever produces a message stamped now.
   4. LEGIBILITY. One idea per cue. Short lines. Nothing that cannot be read
      from twenty-five feet away.
   5. TIME IS ALWAYS VISIBLE. Every era change carries a dated clock op, so the
      months roll — forward or back — and the era holds center-stage whenever
      the phone rests. True black only at preshow, Intermission and the end.
   6. GO LINES ARE UNAMBIGUOUS. A sung line in quotes (the calling fragment),
      or a musical/stage event in CAPS. Instrumental passages auto-play from
      one GO (the `pause` beats are tunable in tech).
   ===================================================================== */
window.L5Y_BUILD = 'build-2026-09-18 · line-by-line';

window.L5Y_SHOW = [

/* ============ 1 · STILL HURTING — CATHY, her iPhone ============ */
{n:1,t:'Still Hurting',who:'cathy',cues:[
 {id:'1.1',kind:'music',trig:'PROLOGUE — the first note of the wedding waltz. SHE is discovered on her phone.',
  what:'AUTO-PLAYS from this one GO (~25 s). Her phone, lit — JUNE 2026, the morning after. Facebook pushes a Memories notification; she gives in and taps it; four cards scroll up one at a time — 2025 Ohio (the card he is not in), 2024 the wedding, 2023 the ring, 2022 the couch. Nothing else to fire until the first bar.',
  hold:'The card timings are the `pause` values in cues.js — stretch or tighten them to the waltz in tech.',
  do:[{op:'device',dev:'iphone',who:'cathy'},{op:'stamp',t:'JUNE 2026'},
      {op:'clock',t:'9:41',d:'Friday, June 12, 2026'},
      {op:'wall',t:'M24 — cast photo of JAMIE — she never changed it'},
      {op:'pause',ms:2600},
      {op:'notif',app:'Facebook',w:'now',title:'Memories',
       t:'You have memories with Jamie Wellerstein to look back on today'},
      {op:'pause',ms:2200},
      {op:'notiftap',to:'memories'},
      {op:'pause',ms:400},
      {op:'mem',scroll:'reluctant',yr:'1 year ago · 2025',who:'Cathy Wellerstein',av:'C',col:'#c2447a',when:'June 12, 2025',
       txt:'Ohio, round two. day one 🎭',media:'M2 — Ohio cast photo, day one — no Jamie',likes:31},
      {op:'pause',ms:2400},
      {op:'mem',scroll:'drag',yr:'2 years ago · 2024',who:'Cathy Wellerstein',av:'C',col:'#c2447a',when:'June 12, 2024',
       txt:'married three weeks and 600 miles apart. worth it.',media:'M4 — the wedding portrait',likes:402},
      {op:'pause',ms:2400},
      {op:'mem',scroll:'peek',yr:'3 years ago · 2023',who:'Cathy Wellerstein',av:'C',col:'#c2447a',when:'June 12, 2023',
       txt:'he asked. I said yes before he finished 💍',media:'M3a — the ring, the rowboat',likes:341},
      {op:'pause',ms:2400},
      {op:'mem',scroll:'flick',yr:'4 years ago · 2022',who:'Cathy Wellerstein',av:'C',col:'#c2447a',when:'June 12, 2022',
       txt:'nine months in and our apartment has a name. it is called The Couch.',media:'M15 — the hideous couch',likes:88}]},
 {id:'1.2',kind:'music',trig:'FIRST BAR OF STILL HURTING — the downbeat, before she sings',
  what:'She puts the phone down. Black — JUNE 2026 holds center-stage while she sings.',
  do:[{op:'black'}]},
 {id:'1.3',kind:'music',trig:'INTERLUDE (m. 58) — the bar after “…like it’s right”. She picks the phone back up.',
  what:'AUTO-PLAYS from this GO (~12 s). Unlock, Messages — the whole list is condolences — his thread, mid-history: days of her asking, all Delivered, all silent. She types it live, hesitant, and SENDS. Delivered.',
  hold:'Nothing to fire until her next sung line. If the interlude runs long, the Delivered sits — let it.',
  do:[{op:'device',dev:'iphone',who:'cathy'},{op:'unlock'},{op:'openapp',icon:'Messages',to:'msglist'},
      {op:'msgrows',rows:[
        {n:'Mom ❤️',p:'call me when you’re up. I love you.',w:'8:02 AM',av:'#e0783f',i:'M',un:true},
        {n:'Dana + girls 🍸',p:'Dana: we’re coming over at 7. non-negotiable.',w:'7:41 AM',av:'#b45ac9',i:'D',un:true},
        {n:'Beth',p:'just heard. I’m so so sorry 💔',w:'Yesterday',av:'#3f7fe0',i:'B'},
        {n:'Grammy',p:'sweetheart. are you eating?',w:'Yesterday',av:'#7b61c9',i:'G',un:true},
        {n:'Aunt Patti',p:'your mother told me. call me, honey',w:'Yesterday',av:'#5aa86b',i:'P'},
        {n:'Jamie',p:'I’m not angry. just talk to me',w:'Wednesday',av:'#8f95a3',i:'J'},
        {n:'Michael (voice)',p:'no lesson this week — I’m out of town',w:'Tuesday',av:'#3f9ea0',i:'M'},
        {n:'Ohio Housing',p:'Re: summer sublet — deposit received',w:'Monday',av:'#5aa86b',i:'O'},
        {n:'CVS Pharmacy',p:'Your prescription is ready for pickup',w:'Monday',av:'#d0454c',i:'C'},
        {n:'Dentist — Dr. Okafor',p:'Reminder: cleaning Jun 22, 2:30 PM',w:'Sunday',av:'#7a8699',i:'D'}]},
      {op:'pause',ms:700},
      {op:'hover',row:'Jamie'},{op:'tap'},{op:'push',to:'thread',contact:'Jamie',sub:'mobile'},
      {op:'history',items:[
        {k:'stamp',t:'May 12|6:40 PM'},{k:'me',t:'your mail is piling up here'},
        {k:'them',t:'I’ll come by this week'},{k:'me',t:'ok'},
        {k:'stamp',t:'May 30|9:12 PM'},{k:'me',t:'the super needs to know about the lease by the 15th'},
        {k:'stamp',t:'Monday|11:02 PM'},{k:'me',t:'are you coming home this weekend?'},
        {k:'stamp',t:'Wednesday|8:15 AM'},{k:'me',t:'please just call me'},
        {k:'stamp',t:'Wednesday|9:30 PM'},{k:'me',t:'I’m not angry. just talk to me'},{k:'rcpt',t:'Delivered'}]},
      {op:'pause',ms:600},
      {op:'stampline',t:'Today|9:41 AM'},{op:'type',pace:'hesitant',t:'I’m not sure that I can do this without you'},
      {op:'pause',ms:350},
      {op:'send'},{op:'rcpt',t:'Delivered'}]},
 {id:'1.4',kind:'lyric',trig:'“Give me a day, Jamie!” — Delivered turns to READ',
  what:'Delivered → READ, 9:44. He is awake. He is holding his phone.',
  hold:'Let the receipt sit alone for a full phrase.',
  do:[{op:'clock',t:'9:44'},{op:'rcptswap',t:'Read 9:44 AM'}]},
 {id:'1.5',kind:'lyric',trig:'“Hang them back on the wall!” — his typing bubble rises',
  what:'His typing bubble rises. He is answering.',
  do:[{op:'typing'}]},
 {id:'1.6',kind:'lyric',trig:'“Had no chance at all.” — it stops',
  what:'It stops. Nothing comes. He read it and put the phone down. The thread stays up through her last verse.',
  hold:'The cruellest silence available in 2026.',
  do:[{op:'untyping'}]},
 {id:'1.7',kind:'music',trig:'FINAL CUTOFF — the last chord of Still Hurting',
  what:'Black on the cutoff. JUNE 2026 holds center-stage until his song rolls it back.',
  do:[{op:'black'}]},
]},

/* ============ 2 · SHIKSA GODDESS — JAMIE, his iPhone ============ */
{n:2,t:'Shiksa Goddess',who:'jamie',cues:[
 {id:'2.1',kind:'music',trig:'TOP OF SHIKSA GODDESS — the first chord, as he enters',
  what:'HIS phone — time rolls BACK five years, JUNE 2026 → SEPTEMBER 2021. Locked, walking home: three unread on the lock screen, her number on top.',
  do:[{op:'device',dev:'iphone',who:'jamie'},
      {op:'clock',t:'11:38',d:'Friday, September 3, 2021'},{op:'stamp',t:'SEPTEMBER 2021'},
      {op:'notif',app:'Messages',w:'3h ago',title:'Mom ❤️',t:'dinner sunday. no excuses.'},
      {op:'notif',app:'Messages',w:'1h ago',title:'Rob',t:'well??? how’d it go'},
      {op:'notif',app:'Messages',w:'56m ago',title:'+1 (917) 555-0148',t:'it’s cathy 😊 — from tonight'}]},
 {id:'2.2',kind:'lyric',trig:'“I’m breaking my mother’s heart” — THE SECOND TIME',
  what:'The phone comes out. Unlock, straight to Messages — her number sits on top, one hour old.',
  do:[{op:'unlock'},{op:'openapp',icon:'Messages',to:'msglist'},
      {op:'msgrows',rows:[
        {n:'+1 (917) 555-0148',p:'it’s cathy 😊 — from tonight',w:'10:42 PM',av:'#8f95a3',i:'#',un:true},
        {n:'Rob',p:'well??? how’d it go',w:'10:12 PM',av:'#3f7fe0',i:'R',un:true},
        {n:'Mom ❤️',p:'dinner sunday. no excuses.',w:'8:05 PM',av:'#e0783f',i:'M',un:true},
        {n:'Dr. Adler',p:'gave your name to an agent — Ms. Whitfield. call her office.',w:'Yesterday',av:'#8a6d10',i:'A'},
        {n:'Elissa Weiss',p:'it was fun, but…',w:'Tuesday',av:'#7b61c9',i:'E'},
        {n:'H. Greenblatt',p:'ok. good luck with the book I guess',w:'Monday',av:'#5aa86b',i:'H'},
        {n:'S. Rosen',p:'I’ll call you this week',w:'2 wks ago',av:'#b45ac9',i:'S'},
        {n:'Columbia workshop',p:'Adam: notes attached for Thursday',w:'2 wks ago',av:'#7a8699',i:'C'}]}]},
 {id:'2.3',kind:'lyric',trig:'“The JCC of Spring Valley…” — the first draft',
  what:'Her thread — one message in it: her number. He types a long, overwrought draft in full.',
  do:[{op:'hover',row:'+1 (917) 555-0148'},{op:'tap'},{op:'push',to:'thread',contact:'+1 (917) 555-0148',sub:'not in contacts'},
      {op:'history',items:[{k:'stamp',t:'Today|10:42 PM'},{k:'them',t:'it’s cathy 😊 — from tonight'}]},
      {op:'clock',t:'11:39'},{op:'type',pace:'hesitant',t:'Tonight was maybe the best night of my whole life'}]},
 {id:'2.4',kind:'lyric',trig:'“…and crumbling to the ground” — deleted; a bolder one',
  what:'Backspaces every character, then tries again, bolder.',
  do:[{op:'wipe'},{op:'type',t:'So when can I see you again. Tomorrow?'}]},
 {id:'2.5',kind:'lyric',trig:'“And my grandfather’s rolling…” — that one goes too; phone away',
  what:'Deleted — failing to write a text on a sidewalk. He pockets the phone: black, SEPTEMBER 2021 holds center while he sings.',
  do:[{op:'wipe'},{op:'clock',t:'11:41'},{op:'pause',ms:700},{op:'black'}]},
 {id:'2.6',kind:'lyric',trig:'“…with the phone in my hand” — it comes back out',
  what:'The thread again. 11:47.',
  do:[{op:'device',dev:'iphone',who:'jamie'},{op:'setapp',to:'thread',contact:'+1 (917) 555-0148',sub:'not in contacts'},
      {op:'history',items:[{k:'stamp',t:'Today|10:42 PM'},{k:'them',t:'it’s cathy 😊 — from tonight'}]},
      {op:'clock',t:'11:47'}]},
 {id:'2.7',kind:'lyric',trig:'“Like an idiot, scared to death” — he finally sends it',
  what:'Two words: “home safe?” — typed and SENT. The finale receives this exact text at 11:48.',
  do:[{op:'clock',t:'11:48'},{op:'stampline',t:'|11:48 PM'},{op:'type',t:'home safe?'},
      {op:'send'},{op:'rcpt',t:'Delivered'}]},
 {id:'2.8',kind:'lyric',trig:'“I’ve been wand’ring through the desert!” — her typing bubble',
  what:'Her typing bubble appears — and stays up.',
  do:[{op:'typing'}]},
 {id:'2.9',kind:'lyric',trig:'“If you had a pierced tongue” — he is ON THE PHONE with Cathy',
  what:'The bubble never resolves as a text — she called instead. Connected call, her number on his screen; the timer ticks.',
  do:[{op:'call',n:'+1 (917) 555-0148',st:'incoming call',dir:'in'},{op:'callState',st:'connected · 00:14'}]},
 {id:'2.10',kind:'lyric',trig:'“…waiting for someone like—” (cut off) — HE HANGS UP; phone away',
  what:'Call Ended, then black — SEPTEMBER 2021 holds center. Nothing else until See I’m Smiling.',
  do:[{op:'black'}]},
]},

/* ============ 3 · SEE I’M SMILING — CATHY & JAMIE (his calls disrupt her time) ============ */
{n:3,t:'See I’m Smiling',who:'both',cues:[
 {id:'3.1',kind:'music',trig:'TOP OF SEE I’M SMILING — the first chord (the pier)',
  what:'No phone for her, by direction. Time rolls FORWARD center-stage — SEPTEMBER 2021 → JULY 2025, her birthday in Ohio — and holds while she sings.',
  do:[{op:'black'},{op:'clock',t:'6:12',d:'Saturday, July 19, 2025'},{op:'stamp',t:'JULY 2025 · OHIO'}]},
 {id:'3.2',kind:'lyric',trig:'“And you’re mine… We’re doing fine.” — JAMIE DIALS. Time snaps back.',
  what:'HIS phone, 2021 — a cold call to the agent, via Dr. Adler. He saved the office number from Adler’s text as “Ms. Whitfield (office)”. Time rolls BACK to SEPTEMBER 2021.',
  do:[{op:'device',dev:'iphone',who:'jamie'},
      {op:'clock',t:'2:41',d:'Tuesday, September 7, 2021'},{op:'stamp',t:'SEPTEMBER 2021'},
      {op:'call',n:'Ms. Whitfield (office)',st:'calling…',dir:'out'}]},
 {id:'3.3',kind:'stage',trig:'JAMIE: “Hi, I’m calling for Ms. Whitfield” — it connects',
  what:'Connected — the timer ticks while the conversation runs.',
  do:[{op:'callState',st:'connected · 00:08'}]},
 {id:'3.4',kind:'stage',trig:'JAMIE: “What’s your address?” — his last words; he hangs up',
  what:'Call Ended; the phone goes. Time ROLLS FORWARD home, center-stage — SEPTEMBER 2021 → JULY 2025.',
  do:[{op:'black'},{op:'clock',t:'6:31',d:'Saturday, July 19, 2025'},{op:'stamp',t:'JULY 2025 · OHIO'}]},
 {id:'3.5',kind:'lyric',trig:'“It’s all right — We’ll have tonight.” — the agent calls HIM back',
  what:'HIS phone again, 2021 — two weeks later (script): an INCOMING call from Ms. Whitfield. Time rolls BACK.',
  do:[{op:'device',dev:'iphone',who:'jamie'},
      {op:'clock',t:'4:18',d:'Tuesday, September 21, 2021'},{op:'stamp',t:'SEPTEMBER 2021'},
      {op:'call',n:'Ms. Whitfield (office)',st:'incoming call',dir:'in'}]},
 {id:'3.6',kind:'stage',trig:'JAMIE: “Hello? This is… Oh, Ms. Whitfield” — he answers',
  what:'Connected. It runs until the thank-you.',
  do:[{op:'callState',st:'connected · 00:21'}]},
 {id:'3.7',kind:'stage',trig:'JAMIE: “Thank you, this is great.” — it ends',
  what:'Again: Call Ended, the phone goes, the centered timeline rolls FORWARD to her evening.',
  do:[{op:'black'},{op:'clock',t:'6:47',d:'Saturday, July 19, 2025'},{op:'stamp',t:'JULY 2025 · OHIO'}]},
 {id:'3.8',kind:'lyric',trig:'“And not do anything at all…” — JAMIE DIALS ROB',
  what:'SCRIPT: he dials — “perplexed but not unhappy.” The lease is up; an apartment WITH Cathy. 2021, pre-move-in. Time rolls BACK.',
  do:[{op:'device',dev:'iphone',who:'jamie'},
      {op:'clock',t:'8:02',d:'Thursday, September 30, 2021'},{op:'stamp',t:'SEPTEMBER 2021'},
      {op:'call',n:'Rob',st:'calling mobile…',dir:'out'}]},
 {id:'3.9',kind:'stage',trig:'JAMIE: “Rob? Yeah, listen.” — Rob picks up',
  what:'Connected — visible through the very end of the vamp.',
  do:[{op:'callState',st:'connected · 01:02'}]},
 {id:'3.10',kind:'music',trig:'DOWNBEAT OF MOVING TOO FAST — he hangs up',
  what:'Call Ended on the downbeat; time rolls one month FORWARD into Moving Too Fast — OCTOBER 2021, center-stage.',
  do:[{op:'black'},{op:'clock',t:'2:14',d:'Friday, October 8, 2021'},{op:'stamp',t:'OCTOBER 2021'}]},
]},

/* ============ 4 · MOVING TOO FAST — JAMIE (with Cathy’s gig call) ============ */
{n:4,t:'Moving Too Fast',who:'both',cues:[
 {id:'4.1',kind:'lyric',trig:'“But oh, oh — what else am I s’pposed to do?” — CATHY DIALS',
  what:'HER phone — MAY 2025 (pinned by David: her backward line, between the pier and the party). Time ROLLS FORWARD from his October 2021 as she cuts in. Dialing Mike Stelmyer; his agency is never named (script).',
  do:[{op:'device',dev:'iphone',who:'cathy'},
      {op:'clock',t:'10:10',d:'Friday, May 9, 2025'},{op:'stamp',t:'MAY 2025'},
      {op:'call',n:'Mike Stelmyer',st:'calling…',dir:'out'}]},
 {id:'4.2',kind:'lyric',trig:'END OF “…what else am I s’pposed to do?” — it connects; she speaks next',
  what:'We see the dial AND the connect; the timer ticks under her call.',
  do:[{op:'callState',st:'connected · 00:15'}]},
 {id:'4.3',kind:'stage',trig:'CATHY: “I’ll call you soon!” — the call ends; back to HIS phone',
  what:'Call Ended; time ROLLS BACK, May 2025 → October 2021 — his phone, locked, ready for the run of wins.',
  do:[{op:'device',dev:'iphone',who:'jamie'},
      {op:'clock',t:'2:14',d:'Friday, October 8, 2021'},{op:'stamp',t:'OCTOBER 2021'}]},
 {id:'4.4',kind:'lyric',trig:'“Found an apartment on Seventy-Third!”',
  what:'Move-in day pops up, both names on the day.',
  do:[{op:'notif',app:'Calendar',w:'now',title:'MOVE-IN DAY 🚚 — W 73rd St',
       t:'Saturday, Oct 16 · 9:00 AM · with Cathy Hiatt'}]},
 {id:'4.5',kind:'lyric',trig:'“The Atlantic Monthly’s printing my first chapter”',
  what:'The Atlantic says yes.',
  do:[{op:'notif',app:'Mail',w:'now',title:'The Atlantic Monthly',t:'We are delighted to publish your excerpt'}]},
 {id:'4.6',kind:'lyric',trig:'“Two thousand bucks without rewriting one word!”',
  what:'The deposit lands.',
  do:[{op:'notif',app:'Chase',w:'now',title:'Chase',t:'You received a deposit of $2,000.00'}]},
 {id:'4.7',kind:'lyric',trig:'“I left Columbia and don’t regret it”',
  what:'The withdrawal confirmation.',
  do:[{op:'notif',app:'Mail',w:'now',title:'Columbia University',t:'Withdrawal processed — Fall term ✓'}]},
 {id:'4.8',kind:'lyric',trig:'“I wrote a book and Sonny Mehta read it!”',
  what:'THE BIGGEST HIT.',
  do:[{op:'notif',app:'Messages',w:'now',title:'Linda Whitfield',t:'SONNY READ IT. CALL ME NOW.'}]},
 {id:'4.9',kind:'music',trig:'FINAL CHORD — the last hit of Moving Too Fast',
  what:'Black. OCTOBER 2021 holds center until her song rolls it forward.',
  do:[{op:'black'}]},
]},

/* ============ 5 · I’M A PART OF THAT — CATHY, her iPhone · ONE THING ============ */
{n:5,t:'I’m a Part of That',who:'cathy',cues:[
 {id:'5.1',kind:'music',trig:'TOP OF I’M A PART OF THAT — the first notes of the intro',
  what:'Time rolls FORWARD center-stage — OCTOBER 2021 → MARCH 2025, the book party — and holds while she sings.',
  do:[{op:'black'},{op:'clock',t:'8:12',d:'Saturday, March 8, 2025'},{op:'stamp',t:'MARCH 2025'}]},
 {id:'5.2',kind:'lyric',trig:'“I’m a part of that.” — THE LAST TIME she sings it, as she picks up the book',
  what:'The one thing this song needs. Her phone: unlock, Books — his novel opens where she left it, the last page. The dedication: “For Cathy.” The last image of the song.',
  hold:'Script direction: she looks briefly at the dedication page, then closes the book. Let the page sit through the final chord.',
  do:[{op:'device',dev:'iphone',who:'cathy'},{op:'unlock'},{op:'openapp',icon:'Books',to:'books'},
      {op:'books',author:'Jamie Wellerstein',page:'For Cathy',pos:'312 of 312',left:'Last page'}]},
 {id:'5.3',kind:'music',trig:'FINAL CHORD — the last note of the song',
  what:'Black. MARCH 2025 holds center.',
  do:[{op:'black'}]},
]},

/* ============ 6 · THE SCHMUEL SONG — JAMIE, his iPhone · the season only ============ */
{n:6,t:'The Schmuel Song',who:'jamie',cues:[
 {id:'6.1',kind:'music',trig:'TOP OF THE SCHMUEL SONG — the tree lights come up, before he speaks',
  what:'His phone, locked — the Christmas wallpaper (M23). Time rolls BACK, MARCH 2025 → DECEMBER 2022. No animations: the phone keeps the season for the whole song.',
  do:[{op:'device',dev:'iphone',who:'jamie'},
      {op:'clock',t:'9:12',d:'Saturday, December 24, 2022'},{op:'stamp',t:'DECEMBER 2022'},
      {op:'wall',t:'M23 — Christmas tree lights'}]},
 {id:'6.2',kind:'music',trig:'FINAL CHORD — after the watch, the last note',
  what:'Black. DECEMBER 2022 holds center.',
  do:[{op:'black'}]},
]},

/* ============ 7 · A SUMMER IN OHIO — CATHY’s laptop · ONE FACETIME ============ */
{n:7,t:'A Summer in Ohio',who:'cathy',cues:[
 {id:'7.1',kind:'music',trig:'TOP OF A SUMMER IN OHIO — the intro vamp; she places the call',
  what:'Cathy’s laptop, Ohio — time rolls FORWARD, DECEMBER 2022 → JUNE 2024. She places the FaceTime call: the RINGING screen, his initial pulsing, no video yet.',
  do:[{op:'device',dev:'macbook',who:'cathy'},
      {op:'clock',t:'9:38',d:'Friday, June 21, 2024'},{op:'stamp',t:'JUNE 2024 · OHIO'},
      {op:'facetime',n:'Jamie',st:'FaceTime…'}]},
 {id:'7.2',kind:'lyric',trig:'“I could have a mansion on a hill” — her first line; HE ANSWERS',
  what:'He answers. The prerecorded FaceTime (V2) plays for the entire number — only Jamie, no Cathy self-view — with the real FaceTime overlays and a ticking call duration.',
  hold:'Nothing else to fire until the final chord. The video carries the number.',
  do:[{op:'ftState',st:'connected',main:'V2 — JAMIE AT HIS DESK · the prerecorded FaceTime plays here'}]},
 {id:'7.3',kind:'music',trig:'FINAL CHORD — the last note; the call ends and she closes the laptop',
  what:'Call Ended card (his initial dimmed), a breath, then the screen goes — JUNE 2024 holds center until the wedding rolls it.',
  do:[{op:'ftState',st:'Call Ended'},{op:'pause',ms:2600},{op:'black'}]},
]},

/* ============ 8 · THE NEXT TEN MINUTES — DUET · time, not animations · then INTERMISSION ============ */
{n:8,t:'The Next Ten Minutes',who:'both',cues:[
 {id:'8.1',kind:'stage',trig:'JAMIE: “No, that one’s Jerry Seinfeld” — his first line, in the rowboat',
  what:'No animations, by direction: the phones only mark WHERE WE ARE IN TIME. Her phone, locked — the engagement day, June 12, 2023 — time rolls BACK from Ohio 2024.',
  do:[{op:'device',dev:'iphone',who:'cathy'},
      {op:'clock',t:'4:44',d:'Monday, June 12, 2023'},{op:'stamp',t:'JUNE 2023'}]},
 {id:'8.2',kind:'lyric',trig:'JAMIE: “For the next ten lifetimes?” — the altar',
  what:'The only date both timelines will ever share — the lock screen rolls FORWARD to Saturday, May 18, 2024.',
  do:[{op:'clock',t:'6:47',d:'Saturday, May 18, 2024'},{op:'stamp',t:'MAY 2024 · THE WEDDING'}]},
 {id:'8.3',kind:'lyric',trig:'CATHY: “Is that one John Lennon?” — back in the boat',
  what:'The clock rolls BACK to the beginning of the piece.',
  do:[{op:'clock',t:'4:44',d:'Monday, June 12, 2023'},{op:'stamp',t:'JUNE 2023'}]},
 {id:'8.4',kind:'music',trig:'FINAL CHORD — the lights fade on the boat. END OF ACT ONE',
  what:'INTERMISSION card. It holds through the break; the first GO of Act Two (9.1) clears it.',
  do:[{op:'intermission'}]},
]},

/* ============ 9 · A MIRACLE WOULD HAPPEN — JAMIE · notifications only ============ */
{n:9,t:'A Miracle Would Happen',who:'jamie',cues:[
 {id:'9.1',kind:'music',trig:'TOP OF ACT TWO — the first notes of the vamp, before he sings',
  what:'The Intermission card goes. His phone, locked — time rolls FORWARD, JUNE 2023 → OCTOBER 2024. Married, at a party, and the phone will not stop. He never touches it; the attention just arrives.',
  do:[{op:'device',dev:'iphone',who:'jamie'},
      {op:'clock',t:'11:22',d:'Friday, October 18, 2024'},{op:'stamp',t:'OCTOBER 2024'}]},
 {id:'9.2',kind:'lyric',trig:'“…suddenly finds you attractive”',
  what:'A reader.',
  do:[{op:'notif',app:'Instagram',w:'now',title:'@a.reader.somewhere',
       t:'okay the ending WRECKED me. how are you real'}]},
 {id:'9.3',kind:'lyric',trig:'“And now they’re banging down your door”',
  what:'And another.',
  do:[{op:'notif',app:'Instagram',w:'now',title:'@lit.with.lena',t:'sent you a message request'}]},
 {id:'9.4',kind:'lyric',trig:'“I’m the grand fromage”',
  what:'The book keeps growing without him.',
  do:[{op:'notif',app:'Goodreads',w:'now',title:'Goodreads',t:'Your book passed 10,000 ratings · ★ 4.6'}]},
 {id:'9.5',kind:'lyric',trig:'“Let’s get a cup of coffee.” — Elise',
  what:'And Elise.',
  do:[{op:'notif',app:'Messages',w:'now',title:'Elise · Ed.',t:'proofs went out 🎉 celebratory drink sometime?'}]},
 {id:'9.6',kind:'lyric',trig:'“It’s a challenge to resist temptation” — THE SECOND TIME (after the party)',
  what:'Front row.',
  do:[{op:'notif',app:'Instagram',w:'now',title:'@novel.annie',t:'front row at your reading tonight 🙋‍♀️'}]},
 {id:'9.7',kind:'music',trig:'FINAL CHORD — the last note of the song',
  what:'Black. OCTOBER 2024 holds center.',
  do:[{op:'black'}]},
]},

/* ============ 10 · CLIMBING UPHILL — CATHY · two texts, two rejections, one flashback ============ */
{n:10,t:'Climbing Uphill',who:'cathy',cues:[
 {id:'10.1',kind:'music',trig:'TOP OF CLIMBING UPHILL — the intro, before her first note',
  what:'Her phone, locked, in the audition hallway — time rolls BACK, OCTOBER 2024 → FEBRUARY 2024. An older sign-in reminder sits on the lock screen; then his text lands on top: “break a leg” — lowercase, three seconds of effort.',
  do:[{op:'device',dev:'iphone',who:'cathy'},
      {op:'clock',t:'9:52',d:'Monday, February 5, 2024'},{op:'stamp',t:'FEBRUARY 2024'},
      {op:'notif',app:'Mail',w:'8:14 AM',title:'Casting Networks',t:'Reminder: sign-in opens 10:00 AM — Equity chorus call'},
      {op:'pause',ms:1100},
      {op:'notif',app:'Messages',w:'now',title:'Jamie 💙',t:'break a leg'}]},
 {id:'10.2',kind:'stage',trig:'CATHY: “Okay, thank you. Thank you so much.” — her first spoken line',
  what:'A rejection lands over the lock screen — last week’s audition, answered. Just enough to read: they are not moving forward.',
  do:[{op:'notif',app:'Mail',w:'now',title:'Meridian Stage Company — Casting',
       t:'Thank you for auditioning. We will not be moving forward at this time, but we hope to see you…'}]},
 {id:'10.3',kind:'lyric',trig:'“Belting as high as they can!”',
  what:'Another one. A callback that went the other way.',
  do:[{op:'notif',app:'Mail',w:'now',title:'Northfield Summer Playhouse',
       t:'Re: your callback — we have decided to go in another direction. We will keep your…'}]},
 {id:'10.4',kind:'lyric',trig:'“Grant me Grace!” — she puts the phone away',
  what:'Black — FEBRUARY 2024 holds center while she sings.',
  do:[{op:'black'}]},
 {id:'10.5',kind:'music',trig:'THE BELL TONE — before the audition where we hear her thoughts',
  what:'FLASHBACK, AUTO-PLAYS from this GO. Time rolls BACK three months, FEBRUARY 2024 → NOVEMBER 2023. Her phone lights: a text from him, long and thoughtful — the night before an earlier callback. She opens it; the thread shows the man he was three months ago.',
  hold:'The contrast IS the cue: three seconds of effort in February, a paragraph in November.',
  do:[{op:'black'},{op:'clock',t:'9:48',d:'Wednesday, November 8, 2023'},{op:'stamp',t:'NOVEMBER 2023'},
      {op:'device',dev:'iphone',who:'cathy'},
      {op:'pause',ms:600},
      {op:'notif',app:'Messages',w:'now',title:'Jamie 💙',
       t:'You are going to walk in there tomorrow and be the best thing they see all week. I mean it. Whatever happens in that room, you are already the real thing — I have known that since the first night. Go get it, and call me the second you are out. I love you.'},
      {op:'pause',ms:1800},
      {op:'notiftap',to:'thread',contact:'Jamie 💙',sub:'mobile'},
      {op:'history',items:[
        {k:'stamp',t:'Tuesday|8:15 PM'},{k:'me',t:'callback thursday. 9am. help'},
        {k:'them',t:'you’ve got this. what are you singing?'},{k:'me',t:'the one you like'},
        {k:'stamp',t:'Today|9:48 PM'},
        {k:'them',t:'You are going to walk in there tomorrow and be the best thing they see all week. I mean it. Whatever happens in that room, you are already the real thing — I have known that since the first night. Go get it, and call me the second you are out. I love you.'}]}]},
 {id:'10.6',kind:'stage',trig:'JAMIE: “Cathy, what are you doing now?” — his phone scene begins',
  what:'The phone goes; time rolls FORWARD home — NOVEMBER 2023 → FEBRUARY 2024 — and holds center to the end of the song.',
  do:[{op:'black'},{op:'clock',t:'9:52',d:'Monday, February 5, 2024'},{op:'stamp',t:'FEBRUARY 2024'}]},
]},

/* ============ 11 · IF I DIDN’T BELIEVE IN YOU — JAMIE · timeline only ============ */
{n:11,t:'If I Didn’t Believe In You',who:'jamie',cues:[
 {id:'11.1',kind:'stage',trig:'JAMIE: “Okay, stop. Cathy, stop.” — his first words',
  what:'Timeline only, by direction. Time rolls FORWARD center-stage — FEBRUARY 2024 → MARCH 2026, the night of the party — and holds for the whole song.',
  do:[{op:'black'},{op:'clock',t:'7:41',d:'Friday, March 6, 2026'},{op:'stamp',t:'MARCH 2026'}]},
]},

/* ============ 12 · I CAN DO BETTER THAN THAT — CATHY · THE DRIVE ============ */
{n:12,t:'I Can Do Better Than That',who:'cathy',cues:[
 {id:'12.1',kind:'music',trig:'TOP OF I CAN DO BETTER THAN THAT — the first note of the vamp',
  what:'Her phone on the dash — Apple Maps, mid-route, New York → the Eastern Shore. Time rolls BACK, MARCH 2026 → NOVEMBER 2021. The drive really moves for the whole song: the puck rides the route, the miles and minutes fall, each maneuver counts down, and the phone’s clock runs 4:05 → 7:45. Arrival lands five minutes after this GO.',
  hold:'`dur` (seconds to arrival) lives on this cue in cues.js — match it to the song in tech. After arrival the screen holds on “You have arrived.”',
  do:[{op:'device',dev:'iphone',who:'cathy'},
      {op:'mapsdrive',key:'12',dur:300,mins:220,miles:214,startMin:965,arrive:'7:45 PM',dest:'St. Michaels — the Eastern Shore'},
      {op:'clock',t:'4:05',d:'Saturday, November 6, 2021'},{op:'stamp',t:'NOVEMBER 2021'}]},
 {id:'12.2',kind:'music',trig:'FINAL CHORD — the last note of the song',
  what:'Black. NOVEMBER 2021 holds center.',
  do:[{op:'black'}]},
]},

/* ============ 13 · NOBODY NEEDS TO KNOW — JAMIE · two beats ============ */
{n:13,t:'Nobody Needs to Know',who:'jamie',cues:[
 {id:'13.1',kind:'music',trig:'TOP OF NOBODY NEEDS TO KNOW — the first note, before he sings',
  what:'Time rolls FORWARD center-stage — NOVEMBER 2021 → JUNE 2026, before dawn. His phone is face-down somewhere it should not be.',
  do:[{op:'black'},{op:'batt',v:9},{op:'clock',t:'6:12',d:'Thursday, June 11, 2026'},{op:'stamp',t:'JUNE 2026'}]},
 {id:'13.2',kind:'lyric',trig:'“Cathy is waiting” — her text lands',
  what:'AUTO-PLAYS from this GO. His phone lights on the nightstand — 9% battery — with her good-morning text. He swipes it away immediately, unread, and the screen goes dark again. JUNE 2026 holds.',
  do:[{op:'device',dev:'iphone',who:'jamie'},
      {op:'notif',app:'Messages',w:'now',title:'Cathy 💛',t:'good morning. can’t wait to see you — what time does your flight land?'},
      {op:'pause',ms:1500},{op:'notifDismiss'},{op:'pause',ms:900},{op:'black'}]},
 {id:'13.3',kind:'lyric',trig:'“…in love with someone like you” — his last line; Find My, location back ON',
  what:'Unlock, Find My, her card — she is in Ohio, and he has not been sharing back. Share My Location → Share Indefinitely. The green check is the last image of the song: the cover-up, filed as devotion.',
  hold:'Location was OFF before the song (we never see him turn it off). Hold on this screen through the final chord; 14.1 takes it away.',
  do:[{op:'device',dev:'iphone',who:'jamie'},{op:'clock',t:'6:31'},{op:'unlock'},
      {op:'openapp',icon:'FindMy',to:'findmy'},
      {op:'findmy',person:{n:'Cathy 💛',loc:'Medina, OH',when:'now',mapLabel:'Medina, Ohio',col:'#c2447a'}},
      {op:'pause',ms:800},
      {op:'btnHover',b:'Share My Location'},
      {op:'sheet',title:'Share your location with Cathy 💛?',opts:['Share for One Hour','Share Until End of Day','Share Indefinitely'],safe:'Cancel'},
      {op:'btnHover',b:'Share Indefinitely'},{op:'btnTap',b:'Share Indefinitely'},
      {op:'findmy',person:{n:'Cathy 💛',loc:'Medina, OH',when:'now',mapLabel:'Medina, Ohio',col:'#c2447a',sharing:'Indefinitely'}}]},
]},

/* ============ 14 · GOODBYE UNTIL TOMORROW / I COULD NEVER RESCUE YOU ====
   DUET. The era flips with the singer; her one animation; his era holds last. */
{n:14,t:'Goodbye Until Tomorrow / I Could Never Rescue You',who:'both',cues:[
 {id:'14.1',kind:'music',trig:'TOP OF THE FINALE — the intro, before her first line',
  what:'The phone goes; time rolls BACK center-stage — JUNE 2026 → SEPTEMBER 2021, the first night — and holds while she sings.',
  do:[{op:'black'},{op:'clock',t:'11:40',d:'Friday, September 3, 2021'},{op:'stamp',t:'SEPTEMBER 2021'}]},
 {id:'14.2',kind:'lyric',trig:'JAMIE: “I called Elise to help me pack my bags” — his first line',
  what:'His half: time rolls FORWARD, SEPTEMBER 2021 → JUNE 2026, his last afternoon.',
  do:[{op:'clock',t:'2:40',d:'Thursday, June 11, 2026'},{op:'stamp',t:'JUNE 2026'}]},
 {id:'14.3',kind:'lyric',trig:'CATHY: “Goodbye until I crawl to your door” — her return',
  what:'Back to her: time rolls BACK to the first night.',
  do:[{op:'clock',t:'11:47',d:'Friday, September 3, 2021'},{op:'stamp',t:'SEPTEMBER 2021'}]},
 {id:'14.4',kind:'lyric',trig:'CATHY: “I will be waiting for you!” — her LAST line before he stands; his text lands',
  what:'THE ONE ANIMATION. Her phone lights on the steps: “home safe?” — the text the house watched him send in Shiksa Goddess. She opens it and starts to answer. SHE IS STILL TYPING when his last verse takes the stage.',
  hold:'Do not send. It is the payoff of Shiksa Goddess, two hours ago.',
  do:[{op:'device',dev:'iphone',who:'cathy'},{op:'clock',t:'11:48'},
      {op:'notif',app:'Messages',w:'now',title:'Jamie',t:'home safe?'},
      {op:'pause',ms:1500},
      {op:'notiftap',to:'thread',contact:'Jamie',sub:'mobile'},
      {op:'history',items:[{k:'stamp',t:'Today|10:42 PM'},{k:'me',t:'it’s cathy 😊 — from tonight'},
                           {k:'stamp',t:'Today|11:48 PM'},{k:'them',t:'home safe?'}]},
      {op:'pause',ms:500},
      {op:'type',pace:'hesitant',t:'safe 😊 tonight was'}]},
 {id:'14.5',kind:'lyric',trig:'JAMIE: “You never noticed how the wind had changed” — he stands',
  what:'The phone goes mid-word. Time rolls FORWARD to JUNE 2026 — the breakup — and holds as the last image while he sings his goodbye.',
  hold:'Hold it. Do not resolve it.',
  do:[{op:'black'},{op:'clock',t:'4:12',d:'Thursday, June 11, 2026'},{op:'stamp',t:'JUNE 2026'}]},
 {id:'14.6',kind:'music',trig:'FINAL BLACKOUT — on the last “Goodbye”',
  what:'True black. End of show.',
  do:[{op:'stamp',t:''},{op:'black'}]},
]},

];
