/* =====================================================================
   THE LAST FIVE YEARS — THE SECOND SCREEN
   SHOW CONTENT · production build (David's notes, Sept 18–19, 2026)

   RULES THIS FILE OBEYS
   1. ONE SONG, ONE DEVICE. The projection shows the singer's screen for the
      whole number. Duets flip by whoever is singing (declared per cue).
   2. NO CUTAWAYS. Jamie's clock runs forward, Cathy's runs backward — the two
      characters are never in the same moment. Enforced by validatePOV().
   3. THE CLOCK IS THE PRESENT. Anything stamped earlier is history and loads
      with the app. Live typing only ever produces a message stamped now.
   4. TIME ONLY EVER CHANGES ON THE CALENDAR. A dated `clock` op rolls the
      torn pages (forward tears, backward settles) while the phone is away; the
      phone appears afterwards, already at the new time. The era reads
      MONTH · YEAR N (years since the night they met — their September).
      Real dates stay in the data so the canon arithmetic holds.
   5. THE PHONE ONLY COMES UP WHEN IT IS USED. Otherwise the calendar holds
      the stage. `stamp` is the calendar's foot line (OHIO, THE WEDDING…).
   6. GO LINES ARE UNAMBIGUOUS. A sung line in quotes (the calling fragment),
      or a musical/stage event in CAPS. Instrumental passages auto-play from
      one GO (the `pause` beats are tunable in tech).
   ===================================================================== */
window.L5Y_BUILD = 'build-2026-09-19 · torn score';

window.L5Y_SHOW = [

/* ============ 1 · STILL HURTING — CATHY, her iPhone ============ */
{n:1,t:'Still Hurting',who:'cathy',cues:[
 {id:'1.1',kind:'music',trig:'PROLOGUE — the first note of the wedding waltz',
  what:'ONE GO. The title page tears off the pad and falls; beneath it the calendar reads JUNE · YEAR 5, the morning after, and holds center-stage through the whole prologue. No phone, no sound.',
  hold:'`ms` on this cue delays the tear after GO (0 = on the GO). Nothing else moves until her verse-two line.',
  do:[{op:'clock',t:'9:41',d:'Friday, June 12, 2026'},{op:'stamp',t:'the morning after'},
      {op:'wall',t:'M24 — cast photo of JAMIE — she never changed it'},
      {op:'prologue',ms:0}]},
 {id:'1.2',kind:'lyric',trig:'“…something wonderful died” — she picks up the phone and sends it',
  what:'AUTO-PLAYS from this GO (~50 s — slowed by direction; every pause is tunable in tech). The calendar docks; her phone rises, locked — a Facebook Memories notification lands and she ignores it. Unlock, Messages (the whole list is condolences), his thread mid-history — days of her asking, all silent. She types it live, hesitant, and SENDS. Delivered.',
  hold:'Nothing to fire until her next sung line. If the verse runs long, the Delivered sits — let it.',
  do:[{op:'device',dev:'iphone',who:'cathy'},
      {op:'pause',ms:900},
      {op:'notif',app:'Facebook',w:'now',title:'Memories',t:'You have memories with Jamie Wellerstein to look back on today'},
      {op:'pause',ms:4500},
      {op:'unlock'},{op:'openapp',icon:'Messages',to:'msglist'},
      {op:'msgrows',rows:[
        {n:'Mom ❤️',p:'call me when you’re up. I love you.',w:'8:02 AM',av:'#e0783f',i:'M',un:true},
        {n:'Dana + girls 🍸',p:'Dana: we’re coming over at 7. non-negotiable.',w:'7:41 AM',av:'#b45ac9',i:'D',un:true},
        {n:'Beth',p:'just heard. I’m so so sorry 💔',w:'Yesterday',av:'#3f7fe0',i:'B'},
        {n:'Grammy',p:'sweetheart. are you eating?',w:'Yesterday',av:'#7b61c9',i:'G',un:true},
        {n:'Aunt Patti',p:'your mother told me. call me, honey',w:'Yesterday',av:'#5aa86b',i:'P'},
        {n:'Jamie',p:'I’m not angry. just talk to me',w:'Yesterday',av:'#8f95a3',i:'J'},
        {n:'Michael (voice)',p:'no lesson this week — I’m out of town',w:'Tuesday',av:'#3f9ea0',i:'M'},
        {n:'Ohio Housing',p:'Re: summer sublet — deposit received',w:'Monday',av:'#5aa86b',i:'O'},
        {n:'CVS Pharmacy',p:'Your prescription is ready for pickup',w:'Monday',av:'#d0454c',i:'C'},
        {n:'Dentist — Dr. Okafor',p:'Reminder: cleaning Jun 22, 2:30 PM',w:'Sunday',av:'#7a8699',i:'D'}]},
      {op:'pause',ms:3500},
      {op:'hover',row:'Jamie'},{op:'pause',ms:1600},{op:'tap'},{op:'push',to:'thread',contact:'Jamie',sub:'mobile'},
      {op:'history',items:[
        {k:'stamp',t:'Sunday|8:20 PM'},{k:'me',t:'porch light’s out again. landlord says tuesday'},{k:'them',t:'ok'},
        {k:'stamp',t:'Tuesday|1:15 PM'},{k:'me',t:'sublet deposit cleared 👍 the room is yours too when you’re here'},{k:'them',t:'👍'},
        {k:'stamp',t:'Yesterday|5:05 AM'},{k:'me',t:'good morning. can’t wait to see you — what time does your flight land?'},
        {k:'stamp',t:'Yesterday|1:30 PM'},{k:'me',t:'landed?'},
        {k:'stamp',t:'Yesterday|4:40 PM'},{k:'me',t:'I read it. please call me'},
        {k:'stamp',t:'Yesterday|9:30 PM'},{k:'me',t:'I’m not angry. just talk to me'},{k:'rcpt',t:'Delivered'}]},
      {op:'pause',ms:3200},
      {op:'stampline',t:'Today|9:41 AM'},{op:'pause',ms:1800},{op:'type',pace:'slow',t:'I’m not sure that I can do this without you'},
      {op:'pause',ms:2600},
      {op:'send'},{op:'rcpt',t:'Delivered'}]},
 {id:'1.3',kind:'lyric',trig:'“Give me a day, Jamie!” — Delivered turns to READ',
  what:'Delivered → READ, 9:44. He is awake. He is holding his phone.',
  hold:'Let the receipt sit alone for a full phrase.',
  do:[{op:'clock',t:'9:44'},{op:'rcptswap',t:'Read 9:44 AM'}]},
 {id:'1.4',kind:'lyric',trig:'“Hang them back on the wall!” — his typing bubble rises',
  what:'His typing bubble rises. He is answering.',
  do:[{op:'typing'}]},
 {id:'1.5',kind:'lyric',trig:'“Had no chance at all.” — it stops',
  what:'It stops. Nothing comes. He read it and put the phone down.',
  hold:'The cruellest silence available in Year 5.',
  do:[{op:'untyping'}]},
 {id:'1.6',kind:'lyric',trig:'“Jamie is over and where can I turn?” — she goes to the memories',
  what:'AUTO-PLAYS from this GO (~40 s — slowed by direction: each card’s caption centers, then the eye drifts down into the photograph). She leaves the thread and opens the Memories the notification offered: four cards scroll past — the dressing-room mirror (last year, Ohio round 2 day 1), the wedding, the ring, and the bear he brought at nine months — and she stays on the bear.',
  hold:'The bear card is the last thing she looks at. Let the camera sit.',
  do:[{op:'openapp',icon:'Facebook',to:'memories'},
      {op:'pause',ms:1800},
      {op:'mem',scroll:'reluctant',yr:'1 year ago',who:'Cathy Wellerstein',av:'C',col:'#c2447a',when:'June 12',
       txt:'Ohio round 2 day 1',media:'M26 — Cathy in the dressing-room mirror',likes:64},
      {op:'pause',ms:5000},
      {op:'mem',scroll:'drag',yr:'2 years ago',who:'Cathy Wellerstein',av:'C',col:'#c2447a',when:'June 12',
       txt:'married three weeks and 600 miles apart. worth it.',media:'M4 — the wedding portrait',likes:402},
      {op:'pause',ms:5000},
      {op:'mem',scroll:'peek',yr:'3 years ago',who:'Cathy Wellerstein',av:'C',col:'#c2447a',when:'June 12',
       txt:'he asked. I said yes before he finished 💍',media:'M3a — the ring, the rowboat',likes:341},
      {op:'pause',ms:5000},
      {op:'mem',scroll:'flick',yr:'4 years ago',who:'Cathy Wellerstein',av:'C',col:'#c2447a',when:'June 12',
       txt:'nine months in. he brought a bear 🧸',media:'M2 — Jamie giving Cathy the bear',likes:88},
      {op:'pause',ms:1800},
      {op:'memgo',i:3}]},
 {id:'1.7',kind:'music',trig:'FINAL CUTOFF — the last chord of Still Hurting',
  what:'The phone drops; the calendar returns to center — JUNE · YEAR 5 holds until his song rolls it back.',
  do:[{op:'black'}]},
]},

/* ============ 2 · SHIKSA GODDESS — JAMIE, his iPhone ============ */
{n:2,t:'Shiksa Goddess',who:'jamie',cues:[
 {id:'2.1',kind:'music',trig:'TOP OF SHIKSA GODDESS — the first chord, as he enters',
  what:'The calendar rolls BACK five years, page by page — JUNE · YEAR 5 → SEPTEMBER · YEAR 1 — then docks, and HIS phone rises, locked, walking home: three unread on the lock screen, her number on top.',
  do:[{op:'clock',t:'11:38',d:'Friday, September 3, 2021'},{op:'stamp',t:'the first night'},
      {op:'device',dev:'iphone',who:'jamie'},
      {op:'notif',app:'Messages',w:'3h ago',title:'Mom ❤️',t:'dinner sunday. no excuses.'},
      {op:'notif',app:'Messages',w:'1h ago',title:'Rob',t:'well??? how’d it go'},
      {op:'notif',app:'Messages',w:'56m ago',title:'+1 (917) 555-0148',t:'it’s cathy 😊 — from tonight'}]},
 {id:'2.2',kind:'lyric',trig:'“I’m breaking my mother’s heart” — THE SECOND TIME',
  what:'ONE PIECE, AUTO-PLAYS from this GO (~50 s). Unlock, Messages, her thread — one message in it: her number. Three drafts die under the backspace key (the overwrought one, the bold one, the honest one) before two words survive: “home safe?” — typed, SENT, Delivered. Then her typing bubble rises… and stays up.',
  hold:'Nothing to fire until her call. The finale receives this exact text at 11:48.',
  do:[{op:'unlock'},{op:'openapp',icon:'Messages',to:'msglist'},
      {op:'msgrows',rows:[
        {n:'+1 (917) 555-0148',p:'it’s cathy 😊 — from tonight',w:'10:42 PM',av:'#8f95a3',i:'#',un:true},
        {n:'Rob',p:'well??? how’d it go',w:'10:12 PM',av:'#3f7fe0',i:'R',un:true},
        {n:'Mom ❤️',p:'dinner sunday. no excuses.',w:'8:05 PM',av:'#e0783f',i:'M',un:true},
        {n:'Dr. Adler',p:'gave your name to an agent — Ms. Whitfield. call her office.',w:'Yesterday',av:'#8a6d10',i:'A'},
        {n:'Elissa Weiss',p:'it was fun, but…',w:'Tuesday',av:'#7b61c9',i:'E'},
        {n:'H. Greenblatt',p:'ok. good luck with the book I guess',w:'Monday',av:'#5aa86b',i:'H'},
        {n:'S. Rosen',p:'I’ll call you this week',w:'2 wks ago',av:'#b45ac9',i:'S'},
        {n:'Columbia workshop',p:'Adam: notes attached for Thursday',w:'2 wks ago',av:'#7a8699',i:'C'}]},
      {op:'pause',ms:1200},
      {op:'hover',row:'+1 (917) 555-0148'},{op:'tap'},{op:'push',to:'thread',contact:'+1 (917) 555-0148',sub:'not in contacts'},
      {op:'history',items:[{k:'stamp',t:'Today|10:42 PM'},{k:'them',t:'it’s cathy 😊 — from tonight'}]},
      {op:'pause',ms:1200},
      {op:'clock',t:'11:39'},{op:'type',pace:'hesitant',t:'Tonight was maybe the best night of my whole life'},
      {op:'pause',ms:3800},{op:'wipe'},{op:'pause',ms:2000},
      {op:'type',t:'So when can I see you again. Tomorrow?'},
      {op:'pause',ms:3400},{op:'wipe'},{op:'pause',ms:1800},
      {op:'clock',t:'11:44'},{op:'type',pace:'hesitant',t:'ok so I know this is fast but'},
      {op:'pause',ms:2600},{op:'wipe'},{op:'pause',ms:4200},
      {op:'clock',t:'11:48'},{op:'stampline',t:'|11:48 PM'},{op:'type',t:'home safe?'},
      {op:'pause',ms:2400},
      {op:'send'},{op:'rcpt',t:'Delivered'},
      {op:'pause',ms:4200},
      {op:'typing'}]},
 {id:'2.3',kind:'lyric',trig:'“If you had a pierced tongue” — he is ON THE PHONE with Cathy',
  what:'The bubble never resolves as a text — she called instead. Incoming, then connected; the timer ticks.',
  do:[{op:'call',n:'+1 (917) 555-0148',st:'incoming call',dir:'in'},{op:'pause',ms:3200},{op:'callState',st:'connected · 00:00'}]},
 {id:'2.4',kind:'lyric',trig:'“…waiting for someone like—” (cut off) — HE HANGS UP; phone away',
  what:'Call Ended, the phone drops, the calendar returns: SEPTEMBER · YEAR 1 holds. Nothing else until See I’m Smiling.',
  do:[{op:'black'}]},
]},

/* ============ 3 · SEE I’M SMILING — CATHY & JAMIE (his calls disrupt her time) ============ */
{n:3,t:'See I’m Smiling',who:'both',cues:[
 {id:'3.1',kind:'music',trig:'TOP OF SEE I’M SMILING — the first chord (the pier)',
  what:'No phone for her, by direction. The calendar rolls FORWARD, page by page — SEPTEMBER · YEAR 1 → JULY · YEAR 4, her birthday in Ohio — and holds while she sings.',
  do:[{op:'black'},{op:'clock',t:'6:12',d:'Saturday, July 19, 2025'},{op:'stamp',t:'Ohio · her birthday'}]},
 {id:'3.2',kind:'lyric',trig:'“And you’re mine… We’re doing fine.” — JAMIE DIALS. Time snaps back.',
  what:'The calendar rolls BACK to SEPTEMBER · YEAR 1 and docks; HIS phone rises already dialing — a cold call to the agent, via Dr. Adler (“Ms. Whitfield (office)”, from Adler’s text). Ringback under it.',
  do:[{op:'clock',t:'2:41',d:'Tuesday, September 7, 2021'},{op:'stamp',t:''},
      {op:'device',dev:'iphone',who:'jamie'},
      {op:'call',n:'Ms. Whitfield (office)',st:'calling…',dir:'out'}]},
 {id:'3.3',kind:'stage',trig:'JAMIE: “Hi, I’m calling for Ms. Whitfield” — it connects',
  what:'Connected — the timer ticks while the conversation runs.',
  do:[{op:'callState',st:'connected · 00:00'}]},
 {id:'3.4',kind:'stage',trig:'JAMIE: “What’s your address?” — his last words; he hangs up',
  what:'Call Ended; the phone drops; the calendar comes back to center and rolls FORWARD home — SEPTEMBER · YEAR 1 → JULY · YEAR 4.',
  do:[{op:'black'},{op:'clock',t:'6:31',d:'Saturday, July 19, 2025'},{op:'stamp',t:'Ohio · her birthday'}]},
 {id:'3.5',kind:'lyric',trig:'“It’s all right — We’ll have tonight.” — the agent calls HIM back',
  what:'The calendar rolls BACK and docks; HIS phone rises with an INCOMING call from Ms. Whitfield — two weeks later (script). The ring under it.',
  do:[{op:'clock',t:'4:18',d:'Tuesday, September 21, 2021'},{op:'stamp',t:''},
      {op:'device',dev:'iphone',who:'jamie'},
      {op:'call',n:'Ms. Whitfield (office)',st:'incoming call',dir:'in'}]},
 {id:'3.6',kind:'stage',trig:'JAMIE: “Hello? This is… Oh, Ms. Whitfield” — he answers',
  what:'Connected. It runs until the thank-you.',
  do:[{op:'callState',st:'connected · 00:00'}]},
 {id:'3.7',kind:'stage',trig:'JAMIE: “Thank you, this is great.” — it ends',
  what:'Again: Call Ended, the phone drops, the calendar rolls FORWARD to her evening.',
  do:[{op:'black'},{op:'clock',t:'6:47',d:'Saturday, July 19, 2025'},{op:'stamp',t:'Ohio · her birthday'}]},
 {id:'3.8',kind:'lyric',trig:'“And not do anything at all…” — JAMIE DIALS ROB',
  what:'SCRIPT: he dials — “perplexed but not unhappy.” The calendar rolls BACK and docks; his phone rises dialing Rob. The lease is up; an apartment WITH Cathy.',
  do:[{op:'clock',t:'8:02',d:'Thursday, September 30, 2021'},{op:'stamp',t:''},
      {op:'device',dev:'iphone',who:'jamie'},
      {op:'call',n:'Rob',st:'calling mobile…',dir:'out'}]},
 {id:'3.9',kind:'stage',trig:'JAMIE: “Rob? Yeah, listen.” — Rob picks up',
  what:'Connected — visible through the very end of the vamp.',
  do:[{op:'callState',st:'connected · 00:00'}]},
 {id:'3.10',kind:'music',trig:'DOWNBEAT OF MOVING TOO FAST — he hangs up',
  what:'Call Ended on the downbeat; the phone drops; one page tears — OCTOBER · YEAR 1, center-stage.',
  do:[{op:'black'},{op:'clock',t:'2:14',d:'Friday, October 8, 2021'},{op:'stamp',t:''}]},
]},

/* ============ 4 · MOVING TOO FAST — JAMIE (with Cathy’s gig call) ============ */
{n:4,t:'Moving Too Fast',who:'both',cues:[
 {id:'4.1',kind:'lyric',trig:'“But oh, oh — what else am I s’pposed to do?” — CATHY DIALS',
  what:'The calendar rolls FORWARD — OCTOBER · YEAR 1 → MAY · YEAR 4 (pinned by David: her backward line, between the pier and the party) — and docks; HER phone rises dialing Mike Stelmyer. His agency is never named (script).',
  do:[{op:'clock',t:'10:10',d:'Friday, May 9, 2025'},{op:'stamp',t:''},
      {op:'device',dev:'iphone',who:'cathy'},
      {op:'call',n:'Mike Stelmyer',st:'calling…',dir:'out'}]},
 {id:'4.2',kind:'lyric',trig:'END OF “…what else am I s’pposed to do?” — it connects; she speaks next',
  what:'We see the dial AND the connect; the timer ticks under her call.',
  do:[{op:'callState',st:'connected · 00:00'}]},
 {id:'4.3',kind:'stage',trig:'CATHY: “I’ll call you soon!” — the call ends; back to HIS phone',
  what:'Call Ended; her phone drops; the calendar rolls BACK — MAY · YEAR 4 → OCTOBER · YEAR 1 — and docks; his phone rises, locked, ready for the run of wins.',
  do:[{op:'black'},{op:'clock',t:'2:14',d:'Friday, October 8, 2021'},{op:'stamp',t:''},
      {op:'device',dev:'iphone',who:'jamie'}]},
 {id:'4.4',kind:'lyric',trig:'“Found an apartment on Seventy-Third!”',
  what:'Move-in day pops up, both names on the day.',
  do:[{op:'notif',app:'Calendar',w:'now',title:'Invitation: MOVE-IN DAY 🚚 — W 73rd St',t:'Cathy Hiatt invited you · Saturday, Oct 16, 9:00 AM'}]},
 {id:'4.5',kind:'lyric',trig:'“The Atlantic Monthly’s printing my first chapter”',
  what:'The Atlantic says yes.',
  do:[{op:'notif',app:'Mail',w:'now',title:'The Atlantic Monthly',t:'We are delighted to publish your excerpt'}]},
 {id:'4.6',kind:'lyric',trig:'“Two thousand bucks without rewriting one word!”',
  what:'The deposit lands.',
  do:[{op:'notif',app:'Chase',w:'now',title:'Chase',t:'You received a deposit of $2,000.00'}]},
 {id:'4.7',kind:'lyric',trig:'“I left Columbia and don’t regret it”',
  what:'The withdrawal confirmation.',
  do:[{op:'notif',app:'Mail',w:'now',title:'Columbia University',t:'Withdrawal processed — Fall term ✓'}]},
 {id:'4.8',kind:'lyric',trig:'“I wrote a book and Sonny Mehta read it!”',
  what:'THE BIGGEST HIT.',
  do:[{op:'notif',app:'Messages',w:'now',title:'Linda Whitfield',t:'SONNY READ IT. CALL ME NOW.'}]},
 {id:'4.9',kind:'music',trig:'FINAL CHORD — the last hit of Moving Too Fast',
  what:'The phone drops; OCTOBER · YEAR 1 holds center until her song rolls it forward.',
  do:[{op:'black'}]},
]},

/* ============ 5 · I’M A PART OF THAT — CATHY · the calendar only ============ */
{n:5,t:'I’m a Part of That',who:'cathy',cues:[
 {id:'5.1',kind:'music',trig:'TOP OF I’M A PART OF THAT — the first notes of the intro',
  what:'Calendar only, by direction (the dedication is cut). The pages roll FORWARD — OCTOBER · YEAR 1 → MARCH · YEAR 4, the book party — and hold for the whole song.',
  do:[{op:'black'},{op:'clock',t:'8:12',d:'Saturday, March 8, 2025'},{op:'stamp',t:'the book party'}]},
]},

/* ============ 6 · THE SCHMUEL SONG — JAMIE, his iPhone · the season only ============ */
{n:6,t:'The Schmuel Song',who:'jamie',cues:[
 {id:'6.1',kind:'music',trig:'TOP OF THE SCHMUEL SONG — the tree lights come up, before he speaks',
  what:'The calendar rolls BACK — MARCH · YEAR 4 → DECEMBER · YEAR 2 — and docks; his phone rises, locked, the Christmas wallpaper (M23). No animations: the phone keeps the season for the whole song.',
  do:[{op:'clock',t:'9:12',d:'Saturday, December 24, 2022'},{op:'stamp',t:'their second Christmas'},
      {op:'device',dev:'iphone',who:'jamie'},
      {op:'wall',t:'M23 — Christmas tree lights'}]},
 {id:'6.2',kind:'music',trig:'FINAL CHORD — after the watch, the last note',
  what:'The phone drops; DECEMBER · YEAR 2 holds center.',
  do:[{op:'black'}]},
]},

/* ============ 7 · A SUMMER IN OHIO — CATHY’s laptop · ONE FACETIME ============ */
{n:7,t:'A Summer in Ohio',who:'cathy',cues:[
 {id:'7.1',kind:'music',trig:'TOP OF A SUMMER IN OHIO — the intro vamp; she places the call',
  what:'The calendar rolls FORWARD — DECEMBER · YEAR 2 → JUNE · YEAR 3 — and docks; her laptop rises and she places the FaceTime call: the RINGING screen, his initial pulsing, the FaceTime ring under it.',
  do:[{op:'clock',t:'9:38',d:'Friday, June 21, 2024'},{op:'stamp',t:'Ohio'},
      {op:'device',dev:'macbook',who:'cathy'},
      {op:'facetime',n:'Jamie 💙',st:'FaceTime…'}]},
 {id:'7.2',kind:'lyric',trig:'“I could have a mansion on a hill” — her first line; HE ANSWERS',
  what:'He answers. The prerecorded FaceTime (V2) plays for the entire number — only Jamie, no Cathy self-view — with the real FaceTime overlays and a ticking call duration.',
  hold:'Nothing else to fire until the final chord. The video carries the number.',
  do:[{op:'ftState',st:'connected',main:'V2 — JAMIE AT HIS DESK · the prerecorded FaceTime plays here'}]},
 {id:'7.3',kind:'music',trig:'FINAL CHORD — the last note; the call ends and she closes the laptop',
  what:'Call Ended (his initial dimmed, the end tone), a breath, then the laptop drops — JUNE · YEAR 3 holds center until the wedding rolls it.',
  do:[{op:'ftState',st:'Call Ended'},{op:'pause',ms:2600},{op:'black'}]},
]},

/* ============ 8 · THE NEXT TEN MINUTES — DUET · the calendar only · then INTERMISSION ============ */
{n:8,t:'The Next Ten Minutes',who:'both',cues:[
 {id:'8.1',kind:'stage',trig:'JAMIE: “No, that one’s Jerry Seinfeld” — his first line, in the rowboat',
  what:'No phones, by direction. The calendar rolls BACK — JUNE · YEAR 3 → JUNE · YEAR 2, the engagement — and holds.',
  do:[{op:'black'},{op:'clock',t:'4:44',d:'Monday, June 12, 2023'},{op:'stamp',t:'the rowboat'}]},
 {id:'8.2',kind:'lyric',trig:'JAMIE: “For the next ten lifetimes?” — the altar',
  what:'The pages tear FORWARD to the only date both timelines will ever share — MAY · YEAR 3 · THE WEDDING.',
  do:[{op:'clock',t:'6:47',d:'Saturday, May 18, 2024'},{op:'stamp',t:'the wedding'}]},
 {id:'8.3',kind:'lyric',trig:'CATHY: “Is that one John Lennon?” — back in the boat',
  what:'The pages settle BACK to the engagement — JUNE · YEAR 2.',
  do:[{op:'clock',t:'4:44',d:'Monday, June 12, 2023'},{op:'stamp',t:'the rowboat'}]},
 {id:'8.4',kind:'music',trig:'FINAL CHORD — the lights fade on the boat. END OF ACT ONE',
  what:'INTERMISSION: the calendar’s top page reads Intermission and holds, still, through the break; the first GO of Act Two (9.1) tears it off.',
  do:[{op:'intermission'}]},
]},

/* ============ 9 · A MIRACLE WOULD HAPPEN — JAMIE · notifications only ============ */
{n:9,t:'A Miracle Would Happen',who:'jamie',cues:[
 {id:'9.1',kind:'music',trig:'TOP OF ACT TWO — the first notes of the vamp, before he sings',
  what:'The pages clear; the calendar lands and rolls FORWARD — JUNE · YEAR 2 → OCTOBER · YEAR 4 — then docks; his phone rises, locked. Married, at a party, and the phone will not stop. He never touches it; the attention just arrives.',
  do:[{op:'clock',t:'11:22',d:'Friday, October 18, 2024'},{op:'stamp',t:'five months married'},
      {op:'device',dev:'iphone',who:'jamie'},{op:'wall',t:'M4 — the wedding portrait'}]},
 {id:'9.2',kind:'lyric',trig:'“…suddenly finds you attractive”',
  what:'A reader.',
  confirm:true,
  do:[{op:'notif',app:'Instagram',w:'now',title:'a.reader.somewhere',t:'commented: okay the ending WRECKED me. how are you real'}]},
 {id:'9.3',kind:'lyric',trig:'“And now they’re banging down your door”',
  what:'And another.',
  do:[{op:'notif',app:'Instagram',w:'now',title:'lit.with.lena',t:'wants to send you a message'}]},
 {id:'9.4',kind:'lyric',trig:'“I’m the grand fromage”',
  what:'The book keeps growing without him — his agent, not a stranger, says so.',
  confirm:true,
  do:[{op:'clock',t:'11:25'},{op:'notif',app:'Messages',w:'now',title:'Linda Whitfield',t:'third printing confirmed. do NOT post it yet 🍾'}]},
 {id:'9.5',kind:'lyric',trig:'“Let’s get a cup of coffee.”',
  what:'And Elise (the editor at Random House — the woman in this verse is unnamed in the score; the screen names her).',
  confirm:true,
  do:[{op:'notif',app:'Messages',w:'now',title:'Elise (Random House)',t:'paperback cover is in 🎉 celebratory drink sometime?'}]},
 {id:'9.6',kind:'lyric',trig:'“It’s a challenge to resist temptation” — THE SECOND TIME (after the party)',
  what:'Front row. (⚠CONFIRM which occurrence of the phrase — David pins it on the Cue Sheet.)',
  confirm:true,
  do:[{op:'clock',t:'11:29'},{op:'notif',app:'Instagram',w:'now',title:'novel.annie',t:'commented: front row at your reading tonight 🙋‍♀️'}]},
 {id:'9.7',kind:'music',trig:'FINAL CHORD — the last note of the song',
  what:'The phone drops; OCTOBER · YEAR 4 holds center.',
  do:[{op:'black'}]},
]},

/* ============ 10 · CLIMBING UPHILL — CATHY · two texts, two rejections, one flashback ============ */
{n:10,t:'Climbing Uphill',who:'cathy',cues:[
 {id:'10.1',kind:'music',trig:'TOP OF CLIMBING UPHILL — the intro, before her first note',
  what:'The calendar rolls BACK — OCTOBER · YEAR 4 → FEBRUARY · YEAR 3 — and docks; her phone rises, locked, in the audition hallway. A sign-in reminder sits on the lock screen; then his text lands on top: “break a leg” — lowercase, three seconds of effort.',
  do:[{op:'clock',t:'9:52',d:'Monday, February 5, 2024'},{op:'stamp',t:'audition season'},
      {op:'device',dev:'iphone',who:'cathy'},
      {op:'notif',app:'Mail',w:'8:14 AM',title:'Casting Networks',t:'Reminder: sign-in opens 10:00 AM — Equity chorus call'},
      {op:'pause',ms:1100},
      {op:'notif',app:'Messages',w:'now',title:'Jamie 💙',t:'break a leg'}]},
 {id:'10.2',kind:'stage',trig:'CATHY: “Okay, thank you. Thank you so much.” — her first spoken line',
  what:'A rejection lands over the lock screen — last week’s audition, answered. Just enough to read: they are not moving forward.',
  do:[{op:'notif',app:'Mail',w:'now',title:'Meridian Stage Company — Casting',
       t:'Thank you for auditioning. We will not be moving forward at this time, but we hope to see you…'}]},
 {id:'10.3',kind:'lyric',trig:'“Belting as high as they can!”',
  what:'Another one. A callback that went the other way.',
  do:[{op:'notif',app:'Mail',w:'now',title:'Northfield Summer Playhouse',
       t:'Re: your callback — we have decided to go in another direction. We will keep your…'}]},
 {id:'10.4',kind:'lyric',trig:'“Grant me Grace!” — she puts the phone away',
  what:'The phone drops; FEBRUARY · YEAR 3 holds center while she sings.',
  do:[{op:'black'}]},
 {id:'10.5',kind:'music',trig:'THE BELL TONE — before the audition where we hear her thoughts',
  what:'FLASHBACK, AUTO-PLAYS from this GO. The pages settle BACK three months — FEBRUARY → NOVEMBER · YEAR 3 — and dock; her phone rises: a text from him, long and thoughtful, the night before an earlier callback. She opens it; the thread shows the man he was three months ago.',
  hold:'The contrast IS the cue: three seconds of effort in February, a paragraph in November.',
  do:[{op:'clock',t:'9:48',d:'Wednesday, November 8, 2023'},{op:'stamp',t:'three months earlier'},
      {op:'device',dev:'iphone',who:'cathy'},
      {op:'pause',ms:600},
      {op:'notif',app:'Messages',w:'now',title:'Jamie 💙',
       t:'You are going to walk in there tomorrow and be the best thing they see all week. I mean it. Whatever happens in that room, you are already the real thing — I have known that since the first night. Go get it, and call me the second you are out. I love you.'},
      {op:'pause',ms:1800},
      {op:'notiftap',to:'thread',contact:'Jamie 💙',sub:'mobile'},
      {op:'history',items:[
        {k:'stamp',t:'Tuesday|8:15 PM'},{k:'me',t:'callback thursday. 9am. help'},
        {k:'them',t:'you’ve got this. what are you singing?'},{k:'me',t:'the one you like'},
        {k:'stamp',t:'Today|9:48 PM'},
        {k:'them',t:'You are going to walk in there tomorrow and be the best thing they see all week. I mean it. Whatever happens in that room, you are already the real thing — I have known that since the first night. Go get it, and call me the second you are out. I love you.'}]}]},
 {id:'10.6',kind:'stage',trig:'JAMIE: “Cathy, what are you doing now?” — his phone scene begins',
  what:'The phone drops; the pages tear FORWARD home — NOVEMBER → FEBRUARY · YEAR 3 — and hold center to the end of the song.',
  do:[{op:'black'},{op:'clock',t:'9:52',d:'Monday, February 5, 2024'},{op:'stamp',t:'audition season'}]},
]},

/* ============ 11 · IF I DIDN’T BELIEVE IN YOU — JAMIE · the calendar only ============ */
{n:11,t:'If I Didn’t Believe In You',who:'jamie',cues:[
 {id:'11.1',kind:'stage',trig:'JAMIE: “Okay, stop. Cathy, stop.” — his first words',
  what:'Calendar only, by direction. The pages tear FORWARD — FEBRUARY · YEAR 3 → MARCH · YEAR 5, the night of the party — and hold for the whole fight.',
  do:[{op:'black'},{op:'clock',t:'7:41',d:'Friday, March 6, 2026'},{op:'stamp',t:'the night of the party'}]},
]},

/* ============ 12 · I CAN DO BETTER THAN THAT — CATHY · THE DRIVE ============ */
{n:12,t:'I Can Do Better Than That',who:'cathy',cues:[
 {id:'12.1',kind:'music',trig:'TOP OF I CAN DO BETTER THAN THAT — the first note of the vamp',
  what:'The calendar rolls BACK — MARCH · YEAR 5 → NOVEMBER · YEAR 1 — and docks; the dash lights up — CarPlay, already navigating: Apple Maps, New York → the Eastern Shore, the car’s display filling the frame. The drive really moves for the whole song: the puck rides the route, the miles and minutes fall, each maneuver counts down, and the dash clock runs 4:05 → 7:45. Arrival lands five minutes after this GO.',
  hold:'`dur` (seconds to arrival) lives on this cue in cues.js — match it to the song in tech. After arrival the screen holds on “You have arrived.”',
  do:[{op:'clock',t:'4:05',d:'Saturday, November 6, 2021'},{op:'stamp',t:'the drive'},
      {op:'device',dev:'carplay',who:'cathy'},
      {op:'mapsdrive',key:'12',dur:300,mins:220,miles:214,startMin:965,arrive:'7:45 PM',dest:'St. Michaels — the Eastern Shore'}]},
 {id:'12.2',kind:'music',trig:'FINAL CHORD — the last note of the song',
  what:'The dash goes dark; NOVEMBER · YEAR 1 holds center.',
  do:[{op:'black'}]},
]},

/* ============ 13 · NOBODY NEEDS TO KNOW — JAMIE · two beats ============ */
{n:13,t:'Nobody Needs to Know',who:'jamie',cues:[
 {id:'13.1',kind:'music',trig:'TOP OF NOBODY NEEDS TO KNOW — the first note, before he sings',
  what:'The pages tear FORWARD — NOVEMBER · YEAR 1 → JUNE · YEAR 5, before dawn — and hold. His phone is face-down somewhere it should not be.',
  do:[{op:'black'},{op:'batt',v:9},{op:'clock',t:'5:05',d:'Thursday, June 11, 2026'},{op:'stamp',t:'before dawn'}]},
 {id:'13.2',kind:'lyric',trig:'“Cathy is waiting” — her text lands',
  what:'AUTO-PLAYS from this GO. The calendar docks; his phone lights on the nightstand — 9% battery — with her good-morning text. He swipes it away immediately, unread, and the phone drops again. JUNE · YEAR 5 holds.',
  do:[{op:'device',dev:'iphone',who:'jamie'},
      {op:'notif',app:'Messages',w:'now',title:'Cathy 💛',t:'good morning. can’t wait to see you — what time does your flight land?'},
      {op:'pause',ms:1500},{op:'notifDismiss'},{op:'pause',ms:900},{op:'black'}]},
 {id:'13.3',kind:'lyric',trig:'“…in love with someone like you” — his last line; Find My, location back ON',
  what:'The calendar docks; his phone rises: unlock, Find My, her card — she is in Ohio, and he has not been sharing back. Share My Location → Share Indefinitely. The green check is the last image of the song: the cover-up, filed as devotion.',
  hold:'Location was OFF before the song (we never see him turn it off). Hold on this screen through the final chord; 14.1 takes it away.',
  do:[{op:'clock',t:'5:24'},{op:'device',dev:'iphone',who:'jamie'},{op:'unlock'},
      {op:'openapp',icon:'FindMy',to:'findmy'},
      {op:'findmy',person:{n:'Cathy 💛',loc:'Mount Orab, OH',when:'now',mapLabel:'Mount Orab, Ohio',col:'#c2447a'}},
      {op:'pause',ms:800},
      {op:'btnHover',b:'Share My Location'},
      {op:'sheet',title:'Share your location with Cathy 💛?',opts:['Share for One Hour','Share Until End of Day','Share Indefinitely'],safe:'Cancel'},
      {op:'btnHover',b:'Share Indefinitely'},{op:'btnTap',b:'Share Indefinitely'},
      {op:'findmy',person:{n:'Cathy 💛',loc:'Mount Orab, OH',when:'now',mapLabel:'Mount Orab, Ohio',col:'#c2447a',sharing:'Indefinitely'}}]},
]},

/* ============ 14 · GOODBYE UNTIL TOMORROW / I COULD NEVER RESCUE YOU ====
   DUET. The calendar flips with the singer; her one animation; his era holds last. */
{n:14,t:'Goodbye Until Tomorrow / I Could Never Rescue You',who:'both',cues:[
 {id:'14.1',kind:'music',trig:'TOP OF THE FINALE — the intro, before her first line',
  what:'The phone drops; the calendar rolls BACK — JUNE · YEAR 5 → SEPTEMBER · YEAR 1, the first night — and holds while she sings.',
  do:[{op:'black'},{op:'clock',t:'11:40',d:'Friday, September 3, 2021'},{op:'stamp',t:'the first night'}]},
 {id:'14.2',kind:'lyric',trig:'JAMIE: “I called Elise to help me pack my bags” — his first line',
  what:'His half: the pages tear FORWARD — SEPTEMBER · YEAR 1 → JUNE · YEAR 5, his last afternoon.',
  do:[{op:'clock',t:'2:40',d:'Thursday, June 11, 2026'},{op:'stamp',t:'the last afternoon'}]},
 {id:'14.3',kind:'lyric',trig:'CATHY: “Goodbye until I crawl to your door” — her return',
  what:'Back to her: the pages settle BACK to the first night.',
  do:[{op:'clock',t:'11:47',d:'Friday, September 3, 2021'},{op:'stamp',t:'the first night'}]},
 {id:'14.4',kind:'lyric',trig:'CATHY: “I will be waiting for you!” — her LAST line before he stands; his text lands',
  what:'THE ONE ANIMATION. The calendar docks; her phone lights on the steps: “home safe?” — the text the house watched him send in Shiksa Goddess. She opens it and starts to answer. SHE IS STILL TYPING when his last verse takes the stage.',
  hold:'Do not send. It is the payoff of Shiksa Goddess, two hours ago.',
  do:[{op:'clock',t:'11:48'},{op:'device',dev:'iphone',who:'cathy'},
      {op:'notif',app:'Messages',w:'now',title:'Jamie',t:'home safe?'},
      {op:'pause',ms:1500},
      {op:'notiftap',to:'thread',contact:'Jamie',sub:'mobile'},
      {op:'history',items:[{k:'stamp',t:'Today|10:42 PM'},{k:'me',t:'it’s cathy 😊 — from tonight'},
                           {k:'stamp',t:'Today|11:48 PM'},{k:'them',t:'home safe?'}]},
      {op:'pause',ms:500},
      {op:'type',pace:'hesitant',t:'safe 😊 tonight was'}]},
 {id:'14.5',kind:'lyric',trig:'JAMIE: “You never noticed how the wind had changed” — he stands',
  what:'The phone drops mid-word; the pages tear FORWARD to JUNE · YEAR 5 — the breakup — and hold as the last image while he sings his goodbye.',
  hold:'Hold it. Do not resolve it.',
  do:[{op:'black'},{op:'clock',t:'4:12',d:'Thursday, June 11, 2026'},{op:'stamp',t:'the last afternoon'}]},
 {id:'14.6',kind:'music',trig:'FINAL BLACKOUT — on the last “Goodbye”',
  what:'Curtain: true black. End of show.',
  do:[{op:'curtain'}]},
]},

];
